spring:
  application:
    name: kafka-consumer

  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      write_dates_as_timestamps: false
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
debug: false

server:
  port: 8020
  compression:
    enabled: true
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/css,text/plain
    min-response-size: 1024
---
#### DEV PROFILE ####
spring:
  profiles:
    active: dev
  kafka:
    consumer:
      group-id: group-1
      auto-offset-reset: earliest


logging:
  file:
    path: /var/log
    name: response-status-logs.txt

kafka:
  topic:
    name: response-status